package com.moulberry.flashback.editor.keybinds;

import java.util.Locale;

import static com.mojang.blaze3d.platform.InputConstants.*;
import static org.lwjgl.sdl.SDLScancode.*;

public class KeybindHelper {

    public static String keyToConfig(int key) {
        return switch (key) {
            default -> "none";
            case Keybind.FAKE_SCROLL_KEY -> "scroll";
            case -MOUSE_BUTTON_LEFT-1 -> "mouseleft";
            case -MOUSE_BUTTON_MIDDLE-1 -> "mousemiddle";
            case -MOUSE_BUTTON_RIGHT-1 -> "mouseright";
            case -MOUSE_BUTTON_4-1 -> "mouse4";
            case -MOUSE_BUTTON_5-1 -> "mouse5";
            case -MOUSE_BUTTON_6-1 -> "mouse6";
            case -MOUSE_BUTTON_7-1 -> "mouse7";
            case -MOUSE_BUTTON_8-1 -> "mouse8";
            case KEY_SPACE         -> "space";
            case KEY_APOSTROPHE    -> "apostrophe";
            case KEY_COMMA         -> "comma";
            case KEY_MINUS         -> "minus";
            case KEY_PERIOD        -> "period";
            case KEY_SLASH         -> "slash";
            case KEY_0             -> "0";
            case KEY_1             -> "1";
            case KEY_2             -> "2";
            case KEY_3             -> "3";
            case KEY_4             -> "4";
            case KEY_5             -> "5";
            case KEY_6             -> "6";
            case KEY_7             -> "7";
            case KEY_8             -> "8";
            case KEY_9             -> "9";
            case KEY_SEMICOLON     -> "semicolon";
            case KEY_EQUALS        -> "equal";
            case KEY_A             -> "a";
            case KEY_B             -> "b";
            case KEY_C             -> "c";
            case KEY_D             -> "d";
            case KEY_E             -> "e";
            case KEY_F             -> "f";
            case KEY_G             -> "g";
            case KEY_H             -> "h";
            case KEY_I             -> "i";
            case KEY_J             -> "j";
            case KEY_K             -> "k";
            case KEY_L             -> "l";
            case KEY_M             -> "m";
            case KEY_N             -> "n";
            case KEY_O             -> "o";
            case KEY_P             -> "p";
            case KEY_Q             -> "q";
            case KEY_R             -> "r";
            case KEY_S             -> "s";
            case KEY_T             -> "t";
            case KEY_U             -> "u";
            case KEY_V             -> "v";
            case KEY_W             -> "w";
            case KEY_X             -> "x";
            case KEY_Y             -> "y";
            case KEY_Z             -> "z";
            case KEY_LBRACKET      -> "leftbracket";
            case KEY_BACKSLASH     -> "backslash";
            case KEY_RBRACKET      -> "rightbracket";
            case KEY_GRAVE         -> "graveaccent";
            case SDL_SCANCODE_INTERNATIONAL1 -> "world1";
            case SDL_SCANCODE_INTERNATIONAL2 -> "world2";
            case KEY_ESCAPE        -> "escape";
            case KEY_RETURN        -> "enter";
            case KEY_TAB           -> "tab";
            case KEY_BACKSPACE     -> "backspace";
            case KEY_INSERT        -> "insert";
            case KEY_DELETE        -> "delete";
            case KEY_RIGHT         -> "right";
            case KEY_LEFT          -> "left";
            case KEY_DOWN          -> "down";
            case KEY_UP            -> "up";
            case KEY_PAGEUP        -> "pageup";
            case KEY_PAGEDOWN      -> "pagedown";
            case KEY_HOME          -> "home";
            case KEY_END           -> "end";
            case KEY_CAPSLOCK      -> "capslock";
            case KEY_SCROLLLOCK    -> "scrolllock";
            case KEY_NUMLOCK       -> "numlock";
            case KEY_PRINTSCREEN   -> "printscreen";
            case KEY_PAUSE         -> "pause";
            case KEY_F1            -> "f1";
            case KEY_F2            -> "f2";
            case KEY_F3            -> "f3";
            case KEY_F4            -> "f4";
            case KEY_F5            -> "f5";
            case KEY_F6            -> "f6";
            case KEY_F7            -> "f7";
            case KEY_F8            -> "f8";
            case KEY_F9            -> "f9";
            case KEY_F10           -> "f10";
            case KEY_F11           -> "f11";
            case KEY_F12           -> "f12";
            case KEY_F13           -> "f13";
            case KEY_F14           -> "f14";
            case KEY_F15           -> "f15";
            case KEY_F16           -> "f16";
            case KEY_F17           -> "f17";
            case KEY_F18           -> "f18";
            case KEY_F19           -> "f19";
            case KEY_F20           -> "f20";
            case KEY_F21           -> "f21";
            case KEY_F22           -> "f22";
            case KEY_F23           -> "f23";
            case KEY_F24           -> "f24";
            case KEY_NUMPAD0       -> "kp0";
            case KEY_NUMPAD1       -> "kp1";
            case KEY_NUMPAD2       -> "kp2";
            case KEY_NUMPAD3       -> "kp3";
            case KEY_NUMPAD4       -> "kp4";
            case KEY_NUMPAD5       -> "kp5";
            case KEY_NUMPAD6       -> "kp6";
            case KEY_NUMPAD7       -> "kp7";
            case KEY_NUMPAD8       -> "kp8";
            case KEY_NUMPAD9       -> "kp9";
            case SDL_SCANCODE_KP_PERIOD  -> "kpdecimal";
            case SDL_SCANCODE_KP_DIVIDE  -> "kpdivide";
            case KEY_MULTIPLY            -> "kpmultiply";
            case SDL_SCANCODE_KP_MINUS   -> "kpsubtract";
            case KEY_ADD                 -> "kpadd";
            case KEY_NUMPADENTER         -> "kpenter";
            case KEY_NUMPADEQUALS        -> "kpequal";
            case KEY_LSHIFT        -> "leftshift";
            case KEY_LCONTROL      -> "leftcontrol";
            case KEY_LALT          -> "leftalt";
            case KEY_LGUI          -> "leftsuper";
            case KEY_RSHIFT        -> "rightshift";
            case KEY_RCONTROL      -> "rightcontrol";
            case KEY_RALT          -> "rightalt";
            case KEY_RGUI          -> "rightsuper";
            case SDL_SCANCODE_MENU -> "menu";
        };
    }

    public static int configToKey(String config) {
        return switch (config.toLowerCase(Locale.ROOT).replace("_", "")) {
            default -> 0;
            case "mouseleft"     -> -MOUSE_BUTTON_LEFT-1;
            case "mousemiddle"   -> -MOUSE_BUTTON_MIDDLE-1;
            case "mouseright"    -> -MOUSE_BUTTON_RIGHT-1;
            case "mouse4"        -> -MOUSE_BUTTON_4-1;
            case "mouse5"        -> -MOUSE_BUTTON_5-1;
            case "mouse6"        -> -MOUSE_BUTTON_6-1;
            case "mouse7"        -> -MOUSE_BUTTON_7-1;
            case "mouse8"        -> -MOUSE_BUTTON_8-1;
            case "scroll"        -> Keybind.FAKE_SCROLL_KEY;
            case "space"         -> KEY_SPACE;
            case "apostrophe"    -> KEY_APOSTROPHE;
            case "comma"         -> KEY_COMMA;
            case "minus"         -> KEY_MINUS;
            case "period"        -> KEY_PERIOD;
            case "slash"         -> KEY_SLASH;
            case "0"             -> KEY_0;
            case "1"             -> KEY_1;
            case "2"             -> KEY_2;
            case "3"             -> KEY_3;
            case "4"             -> KEY_4;
            case "5"             -> KEY_5;
            case "6"             -> KEY_6;
            case "7"             -> KEY_7;
            case "8"             -> KEY_8;
            case "9"             -> KEY_9;
            case "semicolon"     -> KEY_SEMICOLON;
            case "equal"         -> KEY_EQUALS;
            case "a"             -> KEY_A;
            case "b"             -> KEY_B;
            case "c"             -> KEY_C;
            case "d"             -> KEY_D;
            case "e"             -> KEY_E;
            case "f"             -> KEY_F;
            case "g"             -> KEY_G;
            case "h"             -> KEY_H;
            case "i"             -> KEY_I;
            case "j"             -> KEY_J;
            case "k"             -> KEY_K;
            case "l"             -> KEY_L;
            case "m"             -> KEY_M;
            case "n"             -> KEY_N;
            case "o"             -> KEY_O;
            case "p"             -> KEY_P;
            case "q"             -> KEY_Q;
            case "r"             -> KEY_R;
            case "s"             -> KEY_S;
            case "t"             -> KEY_T;
            case "u"             -> KEY_U;
            case "v"             -> KEY_V;
            case "w"             -> KEY_W;
            case "x"             -> KEY_X;
            case "y"             -> KEY_Y;
            case "z"             -> KEY_Z;
            case "leftbracket"   -> KEY_LBRACKET;
            case "backslash"     -> KEY_BACKSLASH;
            case "rightbracket"  -> KEY_RBRACKET;
            case "graveaccent"   -> KEY_GRAVE;
            case "world1"        -> SDL_SCANCODE_INTERNATIONAL1;
            case "world2"        -> SDL_SCANCODE_INTERNATIONAL2;
            case "escape"        -> KEY_ESCAPE;
            case "enter"         -> KEY_RETURN;
            case "tab"           -> KEY_TAB;
            case "backspace"     -> KEY_BACKSPACE;
            case "insert"        -> KEY_INSERT;
            case "delete"        -> KEY_DELETE;
            case "right"         -> KEY_RIGHT;
            case "left"          -> KEY_LEFT;
            case "down"          -> KEY_DOWN;
            case "up"            -> KEY_UP;
            case "pageup"        -> KEY_PAGEUP;
            case "pagedown"      -> KEY_PAGEDOWN;
            case "home"          -> KEY_HOME;
            case "end"           -> KEY_END;
            case "capslock"      -> KEY_CAPSLOCK;
            case "scrolllock"    -> KEY_SCROLLLOCK;
            case "numlock"       -> KEY_NUMLOCK;
            case "printscreen"   -> KEY_PRINTSCREEN;
            case "pause"         -> KEY_PAUSE;
            case "f1"            -> KEY_F1;
            case "f2"            -> KEY_F2;
            case "f3"            -> KEY_F3;
            case "f4"            -> KEY_F4;
            case "f5"            -> KEY_F5;
            case "f6"            -> KEY_F6;
            case "f7"            -> KEY_F7;
            case "f8"            -> KEY_F8;
            case "f9"            -> KEY_F9;
            case "f10"           -> KEY_F10;
            case "f11"           -> KEY_F11;
            case "f12"           -> KEY_F12;
            case "f13"           -> KEY_F13;
            case "f14"           -> KEY_F14;
            case "f15"           -> KEY_F15;
            case "f16"           -> KEY_F16;
            case "f17"           -> KEY_F17;
            case "f18"           -> KEY_F18;
            case "f19"           -> KEY_F19;
            case "f20"           -> KEY_F20;
            case "f21"           -> KEY_F21;
            case "f22"           -> KEY_F22;
            case "f23"           -> KEY_F23;
            case "f24"           -> KEY_F24;
            case "kp0", "num0", "numpad0", "keypad0"           -> KEY_NUMPAD0;
            case "kp1", "num1", "numpad1", "keypad1"           -> KEY_NUMPAD1;
            case "kp2", "num2", "numpad2", "keypad2"           -> KEY_NUMPAD2;
            case "kp3", "num3", "numpad3", "keypad3"           -> KEY_NUMPAD3;
            case "kp4", "num4", "numpad4", "keypad4"           -> KEY_NUMPAD4;
            case "kp5", "num5", "numpad5", "keypad5"           -> KEY_NUMPAD5;
            case "kp6", "num6", "numpad6", "keypad6"           -> KEY_NUMPAD6;
            case "kp7", "num7", "numpad7", "keypad7"           -> KEY_NUMPAD7;
            case "kp8", "num8", "numpad8", "keypad8"           -> KEY_NUMPAD8;
            case "kp9", "num9", "numpad9", "keypad9"           -> KEY_NUMPAD9;
            case "kpdecimal"     -> SDL_SCANCODE_KP_PERIOD;
            case "kpdivide"      -> SDL_SCANCODE_KP_DIVIDE;
            case "kpmultiply"    -> KEY_MULTIPLY;
            case "kpsubtract"    -> SDL_SCANCODE_KP_MINUS;
            case "kpadd"         -> KEY_ADD;
            case "kpenter"       -> KEY_NUMPADENTER;
            case "kpequal"       -> KEY_NUMPADEQUALS;
            case "leftshift"     -> KEY_LSHIFT;
            case "leftcontrol"   -> KEY_LCONTROL;
            case "leftalt"       -> KEY_LALT;
            case "leftsuper"     -> KEY_LGUI;
            case "rightshift"    -> KEY_RSHIFT;
            case "rightcontrol"  -> KEY_RCONTROL;
            case "rightalt"      -> KEY_RALT;
            case "rightsuper"    -> KEY_RGUI;
            case "menu"          -> SDL_SCANCODE_MENU;
        };
    }

}
